/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbn_ocr;

import javax.swing.JOptionPane;
import paintbynumberpro.PBNPuzzle;

/**
 *
 * @author Lynne
 */
public class GrabCluesFromPBNJFrame extends javax.swing.JFrame {

private Puzzle_JFrame myFrame;
private PBNPuzzle myPuzzle;
private boolean is_col_clues;
private int num_clues_for_comparison;

/**
 * Creates new form GrabCluesFromPBNJFrame
 */
public GrabCluesFromPBNJFrame(Puzzle_JFrame theFrame, PBNPuzzle thePuzzle, boolean col_clues,
		int num_clues) {
	initComponents();
	
	myFrame = theFrame;
	myPuzzle = thePuzzle;
	is_col_clues = col_clues;
	num_clues_for_comparison = num_clues;	
			
	// Let's get the total # of filled squares in columns and rows
	int total_col_clues = myPuzzle.GetTotalColClues();
	int total_row_clues = myPuzzle.GetTotalRowClues();
	
	setTitle ("Grab Clues from .pbn File");
	
	this.NumColsJLabel.setText ("Num columns: " + myPuzzle.GetCols());
	this.NumRowsJLabel.setText ("Num rows: " + myPuzzle.GetRows());
	
	this.TotalCluesColJLabel.setText ("Total number of column clues: " + total_col_clues);
	this.TotalCluesRowJLabel.setText ("Total number of row clues: " + total_row_clues);
	
	if (col_clues)
		this.ExtractCluesJLabel.setText ("Extract clues starting from column:");
	else
		this.ExtractCluesJLabel.setText ("Extract clues starting from row:");
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalCluesColJLabel = new javax.swing.JLabel();
        TotalCluesRowJLabel = new javax.swing.JLabel();
        ExtractCluesJLabel = new javax.swing.JLabel();
        StartJTextField = new javax.swing.JTextField();
        NumColsJLabel = new javax.swing.JLabel();
        NumRowsJLabel = new javax.swing.JLabel();
        OKJButton = new javax.swing.JButton();
        CancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        TotalCluesColJLabel.setText("Total clues in column direction:");

        TotalCluesRowJLabel.setText("Total clues in row direction:");

        ExtractCluesJLabel.setText("Extract clues starting from row:");

        StartJTextField.setText("0");

        NumColsJLabel.setText("Num cols:");

        NumRowsJLabel.setText("Num rows:");

        OKJButton.setText("OK");
        OKJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKJButtonActionPerformed(evt);
            }
        });

        CancelJButton.setText("Cancel");
        CancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExtractCluesJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumColsJLabel)
                            .addComponent(TotalCluesColJLabel)
                            .addComponent(NumRowsJLabel)
                            .addComponent(TotalCluesRowJLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumColsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumRowsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCluesColJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCluesRowJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExtractCluesJLabel)
                    .addComponent(StartJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKJButton)
                    .addComponent(CancelJButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelJButtonActionPerformed
		this.dispose();
    }//GEN-LAST:event_CancelJButtonActionPerformed

    private void OKJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKJButtonActionPerformed
        // get starting clue #
		int start_clue = 0;
		try
		{
			start_clue = Integer.parseInt (StartJTextField.getText());
			if (start_clue < 0)
			{
				JOptionPane.showMessageDialog(this, "Please enter a valid integer >= 0",
						"Enter Start Row or Col", JOptionPane.OK_OPTION);
				return;
			} else
			{
				int end_clue = start_clue + num_clues_for_comparison;
				if (is_col_clues && end_clue > myPuzzle.GetCols())
				{
					int max_start = myPuzzle.GetCols() - num_clues_for_comparison;
					JOptionPane.showMessageDialog(this, "Integer must be <= " + max_start,
							"Enter Start Col", JOptionPane.OK_OPTION);	
					return;
				} else if (end_clue > myPuzzle.GetRows())
				{
					int max_start = myPuzzle.GetRows() - num_clues_for_comparison;
					JOptionPane.showMessageDialog(this, "Integer must be <= " + max_start,
							"Enter Start Row", JOptionPane.OK_OPTION);	
					return;
				}
				
				// if we're here then all is good
				myFrame.SetStartingColOrRowForComparison(start_clue, is_col_clues);
			}
		}
		catch (NumberFormatException nfe)
		{
			
		}
    }//GEN-LAST:event_OKJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelJButton;
    private javax.swing.JLabel ExtractCluesJLabel;
    private javax.swing.JLabel NumColsJLabel;
    private javax.swing.JLabel NumRowsJLabel;
    private javax.swing.JButton OKJButton;
    private javax.swing.JTextField StartJTextField;
    private javax.swing.JLabel TotalCluesColJLabel;
    private javax.swing.JLabel TotalCluesRowJLabel;
    // End of variables declaration//GEN-END:variables
}
